name: sen
description: 'Sen: Environment'
publish_to: 'none'
version: 2.0.0
environment:
    sdk: '>=3.4.3 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    delightful_toast: ^1.1.0
    google_fonts: ^6.2.1
    shared_preferences: ^2.3.1
    ffi: ^2.1.2
    async: ^2.11.0
    material_symbols_icons: ^4.2777.1
    intl: any
    path: ^1.9.0
    window_manager: ^0.4.3
    desktop_drop: ^0.5.0
    image: ^4.2.0
    dynamic_color: ^1.7.0
    flutter_localizations:
        sdk: flutter
    page_transition: ^2.1.0
    flutter_local_notifications: ^18.0.0
    local_notifier: ^0.1.6
    flutter_launcher_icons: ^0.14.1
    file_selector: ^1.0.3
    url_launcher: ^6.3.1
    flutter_riverpod: ^2.6.1
    path_provider: ^2.1.5
    flutter_dotenv: ^5.2.1
    shimmer: ^3.0.0
    flutter_native_splash: ^2.4.3
    hooks_riverpod: ^2.6.1
    nil: ^1.1.1
    flutter_hooks: ^0.20.5
    matrix4_transform: ^4.0.1
    riverpod: ^2.6.1
    interactive_box: ^0.4.0
    pie_menu: ^3.2.7
    flutter_box_transform: ^0.4.6
    uuid: ^4.5.1
    stroke_text: ^0.0.3
    custom_mouse_cursor: ^1.1.2
    flex_color_picker: ^3.6.0
    just_audio: ^0.9.42
    audioplayers: ^6.1.0
    number_text_input_formatter: ^1.0.0+8
    drop_down_search_field: ^1.1.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
flutter_launcher_icons:
    android: true
    ios: true
    window: true
    linux: true
    macintosh: true
    image_path: 'assets/images/logo.png'
    remove_alpha_ios: true
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/images/translator/
        - .env
    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/font/GoogleSans-Regular.ttf
        - family: Segoe UI
          fonts:
              - asset: assets/font/SegoeUI.ttf
        - family: PVZ2Font
          fonts:
              - asset: assets/font/fbUsv8C5eI.ttf
